version: '3.8'
services:
  db:
    image: postgres
    volumes:
        - ./data/db:/var/postgressql/data
    ports:
      - "5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: K@vin1309 